# Generated by Django 4.0.3 on 2022-05-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_buyer_alter_listing_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='auctions.listing'),
        ),
    ]
