# Generated by Django 4.0.3 on 2022-05-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_user_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
