# Generated by Django 4.1 on 2022-08-08 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
