# Generated by Django 4.1 on 2022-08-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_created_time_comment_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
