# Generated by Django 4.1 on 2022-08-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bid_created_time_alter_comment_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='staticfiles/auctions/images'),
        ),
    ]
