# Generated by Django 4.1 on 2022-08-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/auctions/images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
